version: '3'
services:

  beegfs-mgmtd:
    container_name: beegfs-mgmtd
    image: beegfs/beegfs-mgmtd:latest
    environment:
      - beegfs_setup_1="beegfs-setup-mgmtd -p /mnt/mgmt_tgt_mgmt01 -C -S mgmt_tgt_mgmt01"
    volumes:
      - /tmp/mgmt_tgt_mgmt01:/mnt/mgmt_tgt_mgmt01
    network_mode: "host"
    command: "storeAllowFirstRunInit=false connDisableAuthentication=true connInterfacesList=eth1 storeMgmtdDirectory=/mnt/mgmt_tgt_mgmt01"
    restart: unless-stopped

  beegfs-meta:
    container_name: beegfs-meta
    image: beegfs/beegfs-meta:latest
    environment:
      - beegfs_setup_1=beegfs-setup-meta -C -p /data/meta_01_tgt_0101 -s 1 -S meta_01
    volumes:
      - /mnt/meta_01_tgt_0101:/data/meta_01_tgt_0101
    network_mode: "host"
    command: "sysMgmtdHost=10.8.33.50 storeAllowFirstRunInit=false connDisableAuthentication=true connInterfacesList=eth1 storeMetaDirectory=/data/meta_01_tgt_0101"
    restart: unless-stopped
    depends_on:
      - beegfs-mgmtd
